client_id = "b08d9508e7d51f3210d149a15e3f3044"
name = "announcement-app"
application_url = "https://announcement-app-6qvm.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "write_products"

[auth]
redirect_urls = [
  "https://announcement-app-6qvm.onrender.com/api/auth/callback"
]
